---

plugins:
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

rules:
  no-console: 0
  react/forbid-prop-types: 0
